import Head from 'next/head'
import BuyConfidence from '../components/BuyConfidence'
import CTA from '../components/CTA'
import GetStartedCTA from '../components/GetStartedCTA'
import Hero from '../components/Hero'
import MeetBoard from '../components/MeetBoard'
import MeetTeam from '../components/MeetTeam'
import Roadmap from '../components/Roadmap'
import SubHero from '../components/SubHero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PetCoin Clone by James Hyatt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main>

      <SubHero />
      <CTA />
      <MeetTeam />
      <MeetBoard />
      <GetStartedCTA />
      <BuyConfidence />
      <Roadmap />
      
    </div>
  )
}
