import Head from 'next/head'
import CTA from '../components/CTA'
import Hero from '../components/Hero'
import SubHero from '../components/SubHero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main>

      <SubHero />
      <CTA />
      
    </div>
  )
}
